const errorCodes = {
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_BODY_REQUEST: "INVALID_BODY_REQUEST",
  INVALID_EMAIL_ADDRESS: "INVALID_EMAIL_ADDRESS",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  INVALID_PASSWORD_LENGTH: "INVALID_PASSWORD_LENGTH",
  SIGNUP_FAILED: "SIGNUP_FAILED",
};

export default errorCodes;
