const errorCodes = {
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_BODY_REQUEST: "INVALID_BODY_REQUEST",
  INVALID_EMAIL_ADDRESS: "INVALID_EMAIL_ADDRESS",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  INVALID_PASSWORD_LENGTH: "INVALID_PASSWORD_LENGTH",
  INVALID_DISPLAY_NAME: "INVALID_DISPLAY_NAME",
  INVALID_DISPLAY_NAME_LENGTH: "INVALID_DISPLAY_NAME_LENGTH",
  SIGNUP_FAILED: "SIGNUP_FAILED",
  NO_REQUEST_HEADER: "NO_REQUEST_HEADER",
  NO_AUTHORIZATION_HEADER: "NO_AUTHORIZATION_HEADER",
  INVALID_AUTHORIZATION: "INVALID_AUTHORIZATION",
  INVALID_ROOM_NAME: "INVALID_ROOM_NAME",
  ROOM_DOES_NOT_EXISTS: "ROOM_DOES_NOT_EXISTS",
  NOT_ALLOWED_TO_DELETE_ROOM: "NOT_ALLOWED_TO_DELETE_ROOM",
  UPLOAD_FILE_FAILED: "UPLOAD_FILE_FAILED",
  INVALID_FILE_NAME: "INVALID_FILE_NAME",
  INVALID_FILE_CONTENT: "INVALID_FILE_CONTENT",
  NOT_ENOUGH_PERMISSION_TO_INVITE_USERS:
    "NOT_ENOUGH_PERMISSION_TO_INVITE_USERS",
  NOT_ENOUGH_PERMISSION_TO_UPLOAD_FILES:
    "NOT_ENOUGH_PERMISSION_TO_UPLOAD_FILES",
  NOT_ENOUGH_PERMISSION_TO_REVOKE_INVITES:
    "NOT_ENOUGH_PERMISSION_TO_REVOKE_INVITES",
  FAILED_TO_INVITE_USER: "FAILED_TO_INVITE_USER",
  INVITE_NOT_FOUND: "INVITE_NOT_FOUND",
  USER_ALREADY_INVITED: "USER_ALREADY_INVITED",
  INVALID_USER_ID_FOR_INVITING_FIELD: "INVALID_USER_ID_FOR_INVITING_FIELD",
  INVALID_FIELD: "INVALID_FIELD",
};

export default errorCodes;
